---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# statcanopener

<!-- badges: start -->
<!-- badges: end -->

The goal of statcanopener is to ...

## Installation

<!-- You can install the released version of statcanopener from [CRAN](https://CRAN.R-project.org) with: -->

You can install the development version of statcanopener from [github](https://github/tweed1e/statcanopener) with:

``` r
# install.packages("remotes")
remotes::install_github("tweed1e/statcanopener)
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(statcanopener)

## basic example code

# any setup? can I just run "get_vector" ?
# need to create crul or handle object for post
# right, so it's really an extension of crul or curl
# with pre-determined options
# funcitons are just lik set-handle

```
